# Create docker compose metabase and save data in external volume

version: '3.7'

services:

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=h2
      - MB_DB_DBNAME=metabase.db
      - MB_DB_PORT=3000
    

# Create MySQL docker compose and save data in external volume


  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: true
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_ETU
      MYSQL_USER: metabase
      MYSQL_PASSWORD: metabase
      
    volumes:
#      - ./dbdata:/var/lib/mysql
      - ./init/etudiants.sql:/docker-entrypoint-initdb.d/etudiants.sql
#      - ./init/2_sakila.sql:/docker-entrypoint-initdb.d/2_sakila.sql
    
    ports:
      - 3306:3306





  
    
