version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: example

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: metabase
    ports:
      - "3300:3300"